# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62e9f741ae3882a3c13798c8067c867e630f65b401a5875ec8982eb102f19f1af423b7eef44c986138bc67ee413b5c5c49abe31b3317c2ecdccf9d4253e637d1

test:
  secret_key_base: a0a96b15a79da6f761490a6ce14c50bd41ad3251959724b5517beff1a0044f5ad762774a5bbe1c180efcb5598093a50d8f67fa09981572704df5e35fa77c8e04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
